### ISSUE TITLE
typo in duplicitous

### ISSUE THREAD

**Issue by riffraff** [jaronilan/stories#4]
the sentence `probably tired to deliberately influence their ranking`  should presumably use `tried` rather than `tired`. 

Not a typo, but something odd for me: you used the form "pro mile" for what I assume is 

https://en.wikipedia.org/wiki/Per_mille

but I have never seen it spelled like that in english, might be an accidental use of the cognate in other languages. Or maybe I just misundersood :)

Enjoyed the story tho, thanks for sharing them!

**Comment by jaronilan** [comment]
Thanks! 

Fixed and reprinted.

Pro Mile came from [Merriam](https://www.merriam-webster.com/dictionary/pro%20mille) indeed via language then English. But since Wikipedia said that Permille may also be used to express a 1000-quantile ("999th permille"), which is exactly what I wanted to express, I changed it to that.
